SELECT A.REST_ID AS REST_ID
, REST_NAME
, FOOD_TYPE
, FAVORITES
, ADDRESS
, B.AVG_S AS SCORE

FROM REST_INFO AS A
, (SELECT REST_ID
        , ROUND(AVG(REVIEW_SCORE), 2) AS AVG_S
  FROM REST_REVIEW
  GROUP BY REST_ID) AS B
  
WHERE A.REST_ID = B.REST_ID
AND A.ADDRESS LIKE '서울%'

GROUP BY A.REST_ID
ORDER BY B.AVG_S DESC, A.FAVORITES DESC;